# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron Relph, Product Designer.
email: aaron@imgonnarelph.com
description: > # this means to ignore newlines until "baseurl:"
  SF based Product Designer currently at GitHub building dev tools. Before that I was designing at Gumroad and before that other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imgonnarelph.com" # the base hostname & protocol for your site
twitter_username: aaronrelph
github_username: imgonnarelph
dribbble_username: aaronrelph

# Build settings
markdown: kramdown
