# Site settings
title: Aaron Relph
page_title: Aaron Relph | Product Designer
email: aaron@imgonnarelph.com
description: > # this means to ignore newlines until "baseurl:"
  I am a product designer in San Francisco, California. I design with usability and
  simplicity in mind. I'm most interested in solving complex problems with unique
  solutions and building meaningful products that have a real impact on people’s lives.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imgonnarelph.com" # the base hostname & protocol for your site
twitter_username: aaronrelph
github_username:  aaronrelph
instagram_username:  aaronrelph
linkedin_username:  aaronrelph

# Build settings
markdown: kramdown
